Updated version of Janino for drools-examples-jdk5 module (it was out of sync with the other drools-* modules and  RunExamplesTest.testHelloWorldDrlExample() was failing  due to NoClassDefFoundError: org/codehaus/janino/Parser$ParseException)